config/routes.rb
Supplierx::Engine.routes.draw do
  
  resources :suppliers do
    collection do
      get :search
      get :search_results
      get :autocomplete
    end
  end

  root :to => 'suppliers#index'
end

app/models/supplierx/supplier.rb
module Supplierx
  class Supplier < ActiveRecord::Base
    attr_accessor :active_noupdate, :quality_system_name
         
    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    belongs_to :quality_system, :class_name => 'Commonx::MiscDefinition'
    belongs_to :quality_system, :class_name => 'Commonx::MiscDefinition'
    
    email_regex = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
      
    validates :name, :short_name, :phone, :fort_token, :presence => true
    validates :name, :short_name, :presence => true, :uniqueness => {:case_sensitive => false, :message => I18n.t('Must be unique!')}
    validates :email, :format     => { :with => email_regex, :message => I18n.t('Wrong email format!') },
                      :uniqueness => { :case_sensitive => false, :message => I18n.t('Duplicate email!') },
                      :if => 'email.present?'
    validates :quality_system_id, :numericality => {:greater_than => 0, :only_integer => true}, :if => 'quality_system_id.present?' 
    validates :supplier_category_id, :numericality => {:greater_than => 0, :only_integer => true}, :if => 'supplier_category_id.present?'
    
    default_scope {where(fort_token: Thread.current[:fort_token])}
    
  end
end

app/controllers/supplierx/application_controller.rb
module Supplierx
  class ApplicationController < ::ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    include Searchx::SearchHelper
    
    before_action :require_signin
    before_action :max_pagination 
    before_action :check_access_right 
    before_action :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_action :delete_session_variable, :only => [:create, :update]   #for parent_record_id & parent_resource in check_access_right
    before_action :page_params, :only => :index
    
    helper_method :return_users, :return_misc_definitions
    
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination', session[:fort_token])
    end   
     
  end
end

app/controllers/supplierx/suppliers_controller.rb
# encoding: utf-8
require_dependency "supplierx/application_controller"

module Supplierx
  class SuppliersController < ApplicationController
    before_action :require_employee
    after_action :info_logger, :except => [:new, :edit, :event_action_result, :wf_edit_result, :search_results, :stats_results, :acct_summary_result]
    
    helper_method :return_misc_definitions
    
    def index
      @title = t('Suppliers')
      @suppliers = params[:supplierx_suppliers][:model_ar_r].page(params[:page]).per_page(@max_pagination)
      @erb_code = find_config_const('supplier_index_view', session[:fort_token], 'supplierx')
    end
  
    def new
      @title = t('New Supplier')
      @supplier = Supplierx::Supplier.new()
      @erb_code = find_config_const('supplier_new_view', session[:fort_token], 'supplierx')
    end
  
    def create
      @supplier = Supplierx::Supplier.new(new_params)
      @supplier.last_updated_by_id = session[:user_id]
      @supplier.fort_token = session[:fort_token]
      if @supplier.save
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=Successfully Saved!")
      else
        flash[:notice] = t('Data Error. Supplier Not Saved!')
        @erb_code = find_config_const('supplier_new_view', session[:fort_token], 'supplierx')
        render 'new'
      end
    end
  
    def edit
      @title = t('Update Supplier')
      @supplier = Supplierx::Supplier.find_by_id(params[:id])
      @erb_code = find_config_const('supplier_edit_view', session[:fort_token], 'supplierx')
    end
  
    def update
      @supplier = Supplierx::Supplier.find_by_id(params[:id])
      @supplier.last_updated_by_id = session[:user_id]
      if @supplier.update_attributes(edit_params)
        redirect_to URI.escape(SUBURI + "/view_handler?index=0&msg=Successfully Updated!")
      else
        flash[:notice] = t('Data Error. Supplier Not Updated!')
        @erb_code = find_config_const('supplier_edit_view', session[:fort_token], 'supplierx')
        render 'edit'
      end
    end
  
    def show
      @title = t('Show Supplier')
      @supplier = Supplierx::Supplier.find_by_id(params[:id])
      @erb_code = find_config_const('supplier_show_view', session[:fort_token], 'supplierx')
    end
    
    def autocomplete
      @parts = Supplierx::Supplier.where("active = ?", true).order(:name).where("name like ?", "%#{params[:term]}%")
      render json: @parts.map(&:name)    
    end  
    
    protected
    
    private
    
    def new_params
      params.require(:supplier).permit(:active, :address, :cell, :contact_name, :contact_info, :email, :fax, :last_eval_date, :main_product, :name, :phone, :quality_system_name, 
                     :short_name, :supply_since, :web, :note, :short_comment, :quality_system_id, :supplier_cagetory_id)
    end
    
    def edit_params
      params.require(:supplier).permit(:active, :address, :cell, :contact_name, :contact_info, :email, :fax, :last_eval_date, :main_product, :name, :phone, :quality_system_name, 
                     :short_name, :supply_since, :web, :note, :short_comment, :quality_system_id, :supplier_category_id)
    end
  end
end

app/helpers/supplierx/application_helper.rb
module Supplierx
  module ApplicationHelper
  end
end

app/helpers/supplierx/suppliers_helper.rb
module Supplierx
  module SuppliersHelper
  end
end

app/views/supplierx/suppliers/_form.html.erb
<% if  @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<h1><%=I18n.t(@title)%></h1>
<%= simple_form_for @supplier do |f| %>    
 
  <%= f.input :name, :label => t('Supplier Name:') %>  
  <%= f.input :short_name, :label => t('Short Name:'), :placeholder => '4-8字' %>
  <%= f.input :contact_name, :label => t('Contact Name:') %> 
  <%= f.input :contact_info, :label => t('Contact Info:'), :input_html => {:rows => 2} %> 
  <%= f.input :supply_since, :label => t('Supply Since:'), :as => :string %>
  <%= f.input :cell, :label => t('Cell Phone:') %>   
  <%= f.input :phone, :label => t('Phone:') %> 
  <%= f.input :fax, :label => t('Fax:') %> 
  <%= f.input :address, :label => t('Address:'), :input_html => { :rows => 2} %>
  <%= f.input :web, :label => t('Web:') %>
  <%= f.input :main_product, :label => t('Main Product：'), :input_html => { :rows => 4} %>   
  <%= f.input :short_comment, :label => t('Short Comment:') %>   
  <%= f.input :quality_system_id, :collection => return_misc_definitions('quality_system'), :label => t('Quality System:'),
                                 :label_method => :name, :value_method => :id %>           
  <% if readonly?(@supplier, 'active')%>
     <%= f.input :active_noupdate, :label => t('Active'), :readonly => true, :required => false, :input_html => {:value => @supplier.active} %>
  <% else %>
     <%= f.input :active, :label => t('Active'), :collection => [[t('Yes'), true], [t('No'), false]]%>
  <% end %>      
  <%= f.input :note, :label => t('Note:'), :input_html => { :rows => 4} %> 
  
  <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  &nbsp;&nbsp;&nbsp;&nbsp;
  <%= f.button :submit, t('Save') , :class => BUTTONS_CLS['action'] %>  
<% end %> 

<% end %> 

app/views/supplierx/suppliers/_form_list.html.erb
<% if  @erb_code %>
<%= render inline: ERB.new(@erb_code).result(binding) %>
<% else %>


<h1><%=I18n.t(@title)%></h1>
<div class="byop_pagination"><%= will_paginate models %></div>
<table class="table table-striped">
  <tr>
    <th></th>
    <th><%=t('Short Name')%></th>
    <th><%=t('Supply Since')%></th>
    <th><%=t('Contact')%></th>
    <th><%=t('Phone')%></th> 
    <th><%=t('Cell Phone')%></th>     
    <th><%=t('Active')%></th>  
    <th><%=t('Email')%></th>
    <th><%=t('Address')%></th>
    <th><%=t('Quality System')%></th>
    <th><%=t('Last Updated By')%></th>
    <th></th>
 
  </tr>

<% models.each do |r| %>
  <tr>
  	
  	<td><%= link_to r.id.to_s, SUBURI + "/view_handler?index=1&url=#{supplier_path(r)}"  %></td> 	
    <td><%= r.short_name %></td>
    <td><%= r.supply_since.strftime("%Y/%m/%d") unless r.supply_since.nil? %></td>
    <td><%= r.contact_name %></td>
    <td><%= r.phone %></td>
    <td><%= r.cell %></td>
    <td><%= r.active ? t('Yes') : t('No')%></td>
    <td><%= r.email %></td>
    <td><%= r.address %></td>
    <td><%= r.quality_system.name if r.quality_system_id.present? %></td> 
    <td><%= r.last_updated_by.name  %></td> 
    <td><%= link_to t('Edit'), SUBURI + "/view_handler?index=1&url=#{edit_supplier_path(r)}", :class => BUTTONS_CLS['action'] if has_action_right?('update', params[:controller], r) %></td>

  </tr>
<% end %>
   <table class="table table-striped">
	  <tr>
	    <th>
  		  <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  		  &nbsp;&nbsp;&nbsp;&nbsp;
  		  <%= link_to t('New Supplier'), SUBURI + "/view_handler?index=1&url=#{new_supplier_path}", :class => BUTTONS_CLS['action'] if has_action_right?('create', params[:controller]) %>
        </th>
	  </tr>
	</table> 


<% end %>

app/views/supplierx/suppliers/_form_new.html.erb
<% if  @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<h1><%=I18n.t(@title)%></h1>
<%= simple_form_for @supplier do |f| %>    
 
  <%= f.input :name, :label => t('Supplier Name:') %>  
  <%= f.input :short_name, :label => t('Short Name:'), :placeholder => '4-8字' %>
  <%= f.input :contact_name, :label => t('Contact Name:') %> 
  <%= f.input :contact_info, :label => t('Contact Info:'), :input_html => {:rows => 2} %> 
  <%= f.input :supply_since, :label => t('Supply Since:'), :as => :string %>
  <%= f.input :cell, :label => t('Cell Phone:') %>   
  <%= f.input :phone, :label => t('Phone:') %> 
  <%= f.input :fax, :label => t('Fax:') %> 
  <%= f.input :address, :label => t('Address:'), :input_html => { :rows => 2} %>
  <%= f.input :web, :label => t('Web:') %>
  <%= f.input :main_product, :label => t('Main Product：'), :input_html => { :rows => 4} %>   
  <%= f.input :short_comment, :label => t('Short Comment:') %>   
  <%= f.input :quality_system_id, :collection => return_misc_definitions('quality_system'), :label => t('Quality System:'),
                                 :label_method => :name, :value_method => :id, :include_blank => true %>  
  <%= f.input :note, :label => t('Note:'), :input_html => { :rows => 4} %>        
  
  <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save') , :class => BUTTONS_CLS['action'] %>  
<% end %>  

<% end %>

app/views/supplierx/suppliers/create.html.erb
<h1>Suppliers#create</h1>
<p>Find me in app/views/supplierx/suppliers/create.html.erb</p>

app/views/supplierx/suppliers/edit.html.erb
<%= render 'form' %>

app/views/supplierx/suppliers/index.html.erb
<%= render partial: 'form_list', locals: {models: @suppliers} %>

app/views/supplierx/suppliers/new.html.erb
<%= render 'form_new' %>

app/views/supplierx/suppliers/show.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>


<h1><%=t('Supplier Info') %></h1>

<p>
  <b><%=t('Name')%></b>
  <%= @supplier.name %>
</p>
<p>
  <b><%=t('Short Name') %></b>
  <%= @supplier.short_name %>
</p>
<p>
  <b><%=t('Supply Since') %></b>
  <%= @supplier.supply_since.strftime("%Y/%m/%d") unless @supplier.supply_since.nil? %>
</p>
<p>
  <b><%=t('Contact') %></b>
  <%= @supplier.contact_name %>
</p>
<p>
  <b><%=t('Cell Phone') %></b>
  <%= @supplier.cell %>
</p>
<p>
  <b><%=t('Phone') %></b>
  <%= @supplier.phone %>
</p>
<p>
  <b><%=t('Fax') %></b>
  <%= @supplier.fax %>
</p>
<p>
  <b><%=t('Address') %></b>
  <%= @supplier.address %>
</p>
<p>
  <b><%=t('Email') %></b>
  <%= @supplier.email %>
</p>
<p>
  <b><%=t('Web') %></b>
  <%= @supplier.web %>
</p>
<p>
  <b><%=t('Main Product') %></b>
  <%= @supplier.main_product %>
</p>
<p>
  <b><%=t('Quality System') %></b>
  <%= @supplier.quality_system.name if @supplier.quality_system_id.present? %>
</p>

<p>
  <b><%=t('Short Comment') %></b>
  <%= @supplier.short_comment %>
</p>
<p>
  <b><%= t('Active') %></b>
  <%= @supplier.active ? t('Yes') : t('No') %>
</p>
<p>
  <b><%= t('Last Updated By') %></b>
  <%= @supplier.last_updated_by.name %>
</p>
<p>
  <b><%= t('Note') %></b>
  <%= @supplier.note %>
</p>
   <table class="table table-striped">
	  <tr>
	    <th>
          <%= link_to t('Back'), SUBURI + "/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action'] %>
   		</th>
	  </tr>
	</table> 


<% end %>

app/views/supplierx/suppliers/update.html.erb
<h1>Suppliers#update</h1>
<p>Find me in app/views/supplierx/suppliers/update.html.erb</p>